(?xml)
(component
	(name "org.freedesktop.IBus.Simple")
	(description "A table based simple engine")
	(exec "/usr/libexec/ibus-engine-simple")
	(version "1.5.26.20220314")
	(author "Peng Huang <shawn.p.huang@gmail.com>")
	(license "GPL")
	(homepage "https://github.com/ibus/ibus/wiki")
	(textdomain "ibus")
    (engines
		(engine
			(name "xkb:us::eng")
			(language "en")
			(license "GPL")
			(author "Peng Huang <shawn.p.huang@gmail.com>")
			(layout "us")
			(longname "English (US)")
			(description "English (US)")
			(icon "ibus-keyboard")
			(rank "50"))
		(engine
			(name "xkb:slatin::eng")
			(language "en")
			(license "GPL")
			(author "Vasileios Pasialiokis")
			(layout "slatin")
			(longname "English (Slatin)")
			(description "English (Slatin)")
			(icon "ibus-keyboard")
			(rank "51"))
		(engine
			(name "xkb:vas::eng")
			(language "en")
			(license "GPL")
			(author "Vasileios Pasialiokis")
			(layout "vas")
			(longname "English (Vas)")
			(description "English (Vas)")
			(icon "ibus-keyboard")
			(rank "52"))
		(engine
			(name "xkb:vas:mods:eng")
			(language "en")
			(license "GPL")
			(author "Vasileios Pasialiokis")
			(layout "vas")
			(layout_variant "modifiers")
			(longname "English (Vas, modifiers swapping)")
			(description "English (Vas, modifiers swapping)")
			(icon "ibus-keyboard")
			(rank "53"))
		(engine
			(name "xkb:sgreek::ell")
			(language "el")
			(license "GPL")
			(author "Vasileios Pasialiokis")
			(layout "sgreek")
			(longname "Greek (Sgreek)")
			(description "Greek (Sgreek)")
			(icon "ibus-keyboard")
			(rank "54"))))
